image: python:3.7-stretch

stages:
  - package

.install_opsi_utils: &install_opsi_utils |
  apt update
  apt -y install wget zsync librsync-dev cpio
  wget "http://obs.uib.gmbh:82/home:/uibmz:/opsi:/4.2:/experimental/Debian_10/amd64/opsi-utils_4.2.0.25-1_amd64.deb"
  apt -y install ./opsi-utils_4.2.0.25-1_amd64.deb
  useradd opsiconfd
  groupadd pcpatch
  groupadd opsiadmin
  adduser opsiconfd pcpatch
  adduser opsiconfd opsiadmin

package:makeopsipackage:
  stage: package
  script:
    - apt -y install curl
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
    - source $HOME/.poetry/env
    - poetry install
    - poetry run opsi-dev-tool -l debug --binary-pull
    #- export VERSION=`cat opsi-dev-tool.yml | grep ...`
    #- cat OPSI/control | awk -v new_version="$VERSION" '/^\[/ { section=$1} {line=$0; if ($1 == "version:" && section == "[Product]"){ line = $1 " " new_version} print line}' > tmp
    #- cat tmp > OPSI/control
    #- rm tmp
    - *install_opsi_utils
    - opsi-makepackage
  artifacts:
    name: opsi-client-agent-package
    paths:
      - "./*.opsi"
