image: python:3.7-stretch

stages:
  - package

.install_opsi_utils: &install_opsi_utils |
  apt update
  apt -y install wget zsync librsync-dev cpio unrar
  wget "http://obs.uib.gmbh:82/home:/uibmz:/opsi:/4.2:/experimental/Debian_10/amd64/opsi-utils_4.2.0.25-1_amd64.deb"
  apt -y install ./opsi-utils_4.2.0.25-1_amd64.deb
  useradd opsiconfd
  groupadd pcpatch
  groupadd opsiadmin
  adduser opsiconfd pcpatch
  adduser opsiconfd opsiadmin

package:makeopsipackage:
  stage: package
  script:
    - apt -y install curl
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
    - source $HOME/.poetry/env
    - poetry run opsi-dev-tool -l debug --binary-pull
    - *install_opsi_utils
    - opsi-makepackage
  artifacts:
    name: opsi-client-agent-package
    paths:
      - "./*.opsi"
