image: python:3.7-stretch

stages:
  - package

.install_opsi_dev_tools: &install_opsi_dev_tools |
  apt update
  apt -y install wget cpio unar
  wget "$OPSIDEVTOOLS_URL_LINUX" -O opsi-dev-tools.tar.gz
  tar -xvf opsi-dev-tools.tar.gz

.install_opsi_utils: &install_opsi_utils |
  apt update
  apt -y install zsync librsync-dev cpio
  ./opsi-dev-tool --binary-pull development opsi-utils linux latest ./
  useradd opsiconfd
  groupadd pcpatch
  groupadd opsiadmin
  adduser opsiconfd pcpatch
  adduser opsiconfd opsiadmin

package:makeopsipackage:
  stage: package
  script:
    - *install_opsi_dev_tools
    - *install_opsi_utils
    - ./opsi-dev-tool -l debug --binary-pull
    - opsi-utils/opsi-makepackage --no-set-rights -l 6
  artifacts:
    name: opsi-client-agent-package
    paths:
      - "./*.opsi"
