#!/bin/bash
#
# postinst script
# This script executes after unpacking files from that archive and registering the product at the server.
#
# The following environment variables can be used to obtain information about the current installation:
#   PRODUCT_ID: id of the current product
#   CLIENT_DATA_DIR: directory which contains the installed client data
#   DEPOT_ID
#   PRODUCT_VERSION
#   PACKAGE_VERSION

TMP_DIR=${CLIENT_DATA_DIR}/../${PRODUCT_ID}.tmp
if [ ! -d $TMP_DIR ]; then
	echo "Nothing to do!"
	exit 0
fi

if [ -d "${TMP_DIR}/custom" ]; then
	echo "Restoring custom dir"
	[ -e "${CLIENT_DATA_DIR}/custom" ] && rm -rf "${CLIENT_DATA_DIR}/custom"
	mv "${TMP_DIR}/custom" ${CLIENT_DATA_DIR}/ || exit 1
fi

echo "Removing temporary files..."
rm -rf "${TMP_DIR}"

# install opsi-client-kiosk package on depot (only if migration folder exists)
if [ -d ${CLIENT_DATA_DIR}/../opsi-client-kiosk/migration ]; then
	rm -df ${CLIENT_DATA_DIR}/../opsi-client-kiosk/migration
	opsi-package-manager -iq ${CLIENT_DATA_DIR}/files/kiosk-package/opsi-client-kiosk_*.opsi
fi
# remove kiosk package from client-agent
rm -rf ${CLIENT_DATA_DIR}/files/kiosk-package

exit 0
