#!/usr/bin/perl -w 

# pragmas
use strict;

# modules
use File::Basename;
use File::Copy;
use Sys::Hostname;
 
# global variables
my $prog;
my $host;
my $addr;
my $ipaddr;
my $datei;
my @lines;
my $line;

$prog = basename $0;
$host = hostname();

#####################
#
# Dateiuebergabe
#
#####################
 
if ($ARGV[0]) {
  if ($ARGV[0] eq "-v") {
    version();
  } elsif ($ARGV[0] eq "-h") {
    help();
  } elsif ($ARGV[0] =~ /^-/) {
    print "Unbekannte Option!\n";
    help();
  }
} 
elsif (!$ARGV[0]){help();}

$addr = (gethostbyname($host))[4];
$ipaddr = join(".", unpack("C4", $addr));

foreach $datei (@ARGV) { 
  @lines = ();

  if (open(FILE,"+<$datei")) {
    print "Setze IP-Adresse $ipaddr in $datei ...\n";
    while ($line = <FILE>) {
#      $line =~ s/(^\.KEY\s\w\s)((\d{1,3}\.){3}\d{1,3})(\:.*$)/$1$ipaddr$4/; 
      $line =~ s/^Set "IP_HOST"="XXX.XXX.XXX.XXX"/Set "IP_HOST"="$ipaddr"/; 
      $line =~ s/^Set "HOST"="SERVERNAME"/Set "HOST"="$host"/; 
      push(@lines, $line);
    }
    seek (FILE,0,0);
    truncate (FILE,0);
    print FILE @lines;
    close(FILE);
  } else {
    print "$datei: $! \n";
  }
}

############################
#
# FUNKTIONEN
# 
############################
 
 
sub version {
 print "$prog Version 1.993 22.04.2002 (c) J.Weintz\n";
 exit;
}
 
sub help {
 print "Aufruf: $prog [Optionen] [Dateiliste]\n";
 print "Optionen:  --   wird ignoriert\n";
 print "           -v   gibt Versionskennung aus\n";
 print "           -h   gibt diese Hilfe aus\n";
 print "$prog setzt die eigene IP-Adresse in INCOM-Bootprom-Menu-Dateien ein.\n";
 exit;
}
 
